spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: 'jdbc:oracle:thin:@localhost:1521:xe'
    username: 'crm'
    password: 'C1Sd8serv1'
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: 'org.hibernate.dialect.Oracle10gDialect'